version: "3"
services:
    static-homepage:
        image: nginx:alpine
        container_name: static-homepage
        ports:
            - 80:80
        volumes:
            - ./src:/usr/share/nginx/html
