version: "3"
services:
    static-homepage:
        image: nginx:alpine
        container_name: static-homepage
        ports:
            - 8090:80
        volumes:
            - ./src:/usr/share/nginx/html
        networks:
            - nginx
    networks:
        nginx:
            external: true
            name: nginx
