version: "3"
services:
    static-homepage:
        image: nginx
        container_name: static-homepage
        ports:
            - 8080:80
        volumes:
            - ./src:/usr/share/nginx/html
