version: "3"
services:
    static-homepage:
        build: .
        container_name: static-homepage
        ports:
            - 80:80
        volumes:
            - ./src:/usr/share/nginx/html
        networks:
            - nginx
networks:
    nginx:
        external: true
        name: nginx
